In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3], [-2, 4, -5], [4,7,11]])
A

array([[ 1,  2,  3],
       [-2,  4, -5],
       [ 4,  7, 11]])

In [4]:
# Transpose of A
A.T

array([[ 1, -2,  4],
       [ 2,  4,  7],
       [ 3, -5, 11]])

In [5]:
A.diagonal()  # Main Diagonal Elements of A

array([ 1,  4, 11])

In [6]:
A.trace()    # sum of the main diagonal elements in A

16

In [7]:
A.diagonal().sum()   # built-in numpy function

16

In [8]:
np.sum(A.diagonal())  # Numpy Univ. fucntion

16

In [9]:
sum(A.diagonal())  # core Python funtion

16

In [11]:
A

array([[ 1,  2,  3],
       [-2,  4, -5],
       [ 4,  7, 11]])

In [14]:
np.flipud(A)   # Flip A upside-down

array([[ 4,  7, 11],
       [-2,  4, -5],
       [ 1,  2,  3]])

In [15]:
np.flipud(A).diagonal()  # this how we can fetch the anti-diagonal elements

array([4, 4, 3])

In [16]:
np.fliplr(A)    # Flip A  left-right

array([[ 3,  2,  1],
       [-5,  4, -2],
       [11,  7,  4]])

In [19]:
np.linalg.det(A)   # Determinant of A

-6.999999999999998

In [20]:
np.linalg.det(np.fliplr(A))    # Determinant of the Flipped-A

6.999999999999995

In [21]:
A

array([[ 1,  2,  3],
       [-2,  4, -5],
       [ 4,  7, 11]])

In [22]:
A + 100  # Scalr addition to matrix A

array([[101, 102, 103],
       [ 98, 104,  95],
       [104, 107, 111]])

In [25]:
100 + A  # ordering doesn't matter for scaler operations (since the operations are elelment-wise)

array([[101, 102, 103],
       [ 98, 104,  95],
       [104, 107, 111]])

In [23]:
A - 10  # Scalr substraction to matrix A

array([[ -9,  -8,  -7],
       [-12,  -6, -15],
       [ -6,  -3,   1]])

In [24]:
5* A  # Scalr multiplication to matrix A

array([[  5,  10,  15],
       [-10,  20, -25],
       [ 20,  35,  55]])

In [27]:
B = A.T
B

array([[ 1, -2,  4],
       [ 2,  4,  7],
       [ 3, -5, 11]])

In [28]:
A + B  # Matrix Addition (always element-wise, hence the matrix dimensions MUST ALWAYS MATCH EXACTLY)

array([[ 2,  0,  7],
       [ 0,  8,  2],
       [ 7,  2, 22]])

In [29]:
A - B  # Matrix Substraction (always element-wise, hence the matrix dimensions MUST ALWAYS MATCH EXACTLY)

array([[  0,   4,  -1],
       [ -4,   0, -12],
       [  1,  12,   0]])

In [30]:
A * B  # Matrix Multiplication ELEMENT-Wise (Hadamard Product)

array([[  1,  -4,  12],
       [ -4,  16, -35],
       [ 12, -35, 121]])

In [33]:
B*A    # for element-wise the sequence of operation doesn't matter

array([[  1,  -4,  12],
       [ -4,  16, -35],
       [ 12, -35, 121]])

In [31]:
# Proper matrix multiplication
A.dot(B)

array([[ 14,  -9,  51],
       [ -9,  45, -35],
       [ 51, -35, 186]])

In [34]:
np.matmul(A, B)   # Proper matrix multiplication

array([[ 14,  -9,  51],
       [ -9,  45, -35],
       [ 51, -35, 186]])

In [36]:
np.dot(A, B)

array([[ 14,  -9,  51],
       [ -9,  45, -35],
       [ 51, -35, 186]])

In [32]:
B.dot(A)

array([[ 21,  22,  57],
       [ 22,  69,  63],
       [ 57,  63, 155]])

In [37]:
np.matmul(B, A)

array([[ 21,  22,  57],
       [ 22,  69,  63],
       [ 57,  63, 155]])

In [38]:
A/20  # scaler division

array([[ 0.05,  0.1 ,  0.15],
       [-0.1 ,  0.2 , -0.25],
       [ 0.2 ,  0.35,  0.55]])

In [39]:
A/B  # elelment-wise division

array([[ 1.        , -1.        ,  0.75      ],
       [-1.        ,  1.        , -0.71428571],
       [ 1.33333333, -1.4       ,  1.        ]])

In [40]:
A[:,:2]  # All rows and fist 2 columns of A

array([[ 1,  2],
       [-2,  4],
       [ 4,  7]])

In [41]:
B1 = A[:,:2] 

In [42]:
A.dot(B1)  

array([[  9,  31],
       [-30, -23],
       [ 34, 113]])

In [43]:
B1.dot(A)

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [44]:
A

array([[ 1,  2,  3],
       [-2,  4, -5],
       [ 4,  7, 11]])

In [45]:
np.linalg.inv(A)

array([[-11.28571429,   0.14285714,   3.14285714],
       [ -0.28571429,   0.14285714,   0.14285714],
       [  4.28571429,  -0.14285714,  -1.14285714]])

In [46]:
A1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np.linalg.inv(A1)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [48]:
0.3 - 0.2 - 0.1

-2.7755575615628914e-17

In [50]:
print(np.finfo(float).eps)   # smallest floating-point number possible in your computer
# Resolution limit in Python

2.220446049250313e-16


In [49]:
np.linalg.det(A1)  # the deteminant of this matrix is actually 0.

-9.51619735392994e-16

In [51]:
A2 = np.array([[1,2,3], [4,5,6], [2,4,6]])
A2

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6]])

In [52]:
np.linalg.det(A2) 

0.0

In [53]:
np.linalg.inv(A1) 

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

# Some Matrix Creation Functions

In [56]:
np.zeros(3)  # 1D array of zeros

array([0., 0., 0.])

In [55]:
np.zeros((3,4))  # 2D array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
100*np.ones((3,4)) 

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [62]:
I = np.eye(4)
I.dtype

dtype('float64')

In [61]:
v = [1,2,3,4]
np.diag(v)    #create a diagonal matrix with the supplied vector

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [63]:
# create an array of numbers from 10 to 100 with an increment of 10
np.arange(10, 100, 10)   # start_num, stop_num, increment

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
np.arange(10, 101, 10) 

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [65]:
np.arange(100, 1, -20) 

array([100,  80,  60,  40,  20])

# Linear Algebra

In [66]:
# Matrix Rank
A

array([[ 1,  2,  3],
       [-2,  4, -5],
       [ 4,  7, 11]])

In [67]:
np.linalg.matrix_rank(A)

3

In [69]:
A2

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6]])

In [70]:
np.linalg.matrix_rank(A2)

2

In [72]:
A2[0, :]   # fetching the 1st row

array([1, 2])

In [73]:
A2[-1, :]   # fetching the last row

array([2, 4, 6])

In [74]:
A2[:, -1]   # fetching all the rows of the last col

array([3, 6, 6])

In [75]:
100*A2[:, -1]

array([300, 600, 600])

In [76]:
A2

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6]])

In [77]:
A2[:,0] = 5*A2[:, -1] + 3*A2[:, 1]
A2

array([[21,  2,  3],
       [45,  5,  6],
       [42,  4,  6]])

In [78]:
A2[:,-1] = 5*A2[:, 1]
A2

array([[21,  2, 10],
       [45,  5, 25],
       [42,  4, 20]])

In [80]:
A2[:,0] = 5*A2[:, -1] + 3*A2[:, 1]
A2

array([[ 56,   2,  10],
       [140,   5,  25],
       [112,   4,  20]])

In [81]:
np.linalg.matrix_rank(A2)

1

# Solving System of Linear Equations

2x + 3y + 5z = 10

3x + 2y + 1z = 8

2x + 1y + 2z = 6


In [83]:
# Define your matrices
A = np.array([
    [2, 3, 5],
    [3, 2, 1],
    [2, 1, 2]])

In [90]:
B = np.array([10, 8, 6]).reshape(-1, 1)
B

array([[10],
       [ 8],
       [ 6]])

In [91]:
# x = inverse of A * B 
x = np.linalg.inv(A).dot(B)
x

array([[1.81818182],
       [0.90909091],
       [0.72727273]])

In [92]:
x.round(2)

array([[1.82],
       [0.91],
       [0.73]])

In [93]:
np.linalg.solve(A, B)   # solve() can be used to solve system og linear equations

array([[1.81818182],
       [0.90909091],
       [0.72727273]])